### ISSUE TITLE
templateUser = kuberos / frontend manually shows email

### ISSUE THREAD

**Issue by john-delivuk** [negz/kuberos#17]
Not sure which is the right answer here but your front end "authenticate manually section" shows the users configured id, where as when you get your kubecfg file, it will be kuberos, which raises the bar for quick and simple credentials updates, and a little sloppy, not sure which you prefer, but possibly using one in both places. 

As always thanks for everything!

**Comment by negz** [comment]
Good point! I think that's a historical artifact - I used to use `someusername` everywhere, but then changed to `kuberos`. Happy to change it for consistency - any preference?

**Comment by arnisoph** [comment]
fixed by merging #20
