### ISSUE TITLE
Automatically update kubeconfig

### ISSUE THREAD

**Issue by arnisoph** [negz/kuberos#18]
Hi,

I need a solution that automatically updates the kubeconfig so the user doesn't need to do any further step after authentication.

As a first step I'd patch kuberos.go to do so. Do you have any (other) implementation ideas?

**Comment by negz** [comment]
Hi @bechtoldt! I don't quite follow your idea. Could you elaborate?

Hypothetically with Kuberos the user should simply need to authenticate once and save the generated kubeconfig file as `~/.kube/config`. From there the OIDC refresh token should take care of ensuring their credentials are up to date - they should not need to use Kuberos again unless the set of clusters it provides access to change somehow.

**Comment by negz** [comment]
@bechtoldt Upon rereading your request it seems like you might be looking for some way to update the `~/.kube/config` file on disk when the browser based Kuberos authentication flow completes? I'm afraid I don't think that's possible. There are CLI-based tools like https://github.com/micahhausler/k8s-oidc-helper that can do what you need, though.

I'm going to close this as I don't think it's impossible, but please feel free to reopen this issue if I've misunderstood you.
