### ISSUE TITLE
Consider an "Authenticate Manually" block for adding the cluster as well

### ISSUE THREAD

**Issue by SEJeff** [negz/kuberos#21]
I've got users who currently have a CoreOS tectonic cluster defined in their `~/.kube/config`. I'm in the very slow process of migrating to bare metal RHEL and open source k8s with dex + kuberos. Downloading the config from kuberos will blow away their existing config and the manual instructions only are good for configs with a single cluster, but a new user.

**Comment by negz** [comment]
@SEJeff I _think_ this would be a good idea. Could you give me an example of the `kubectl` commands we'd need to include in such output here?

One alternative to avoid blowing away the existing `~/.kube/config` is to save the downloaded config to `~/.kube/config-kuberos` or similar and `export KUBECONFIG=~/.kube/config:~/.kube/config-kuberos` to have `kubectl` use a big combined kubeconfig containing the two files.

**Comment by SEJeff** [comment]
Funnily enough, for my internal user documentation, I'm asking them to just set `KUBECONIFG` and point it to both files.

The issue is that we have two clusters, one running CoreOS Tectonic, and one vanilla kubernetes cluster we built. The kuberos instructions for manually adding the user don't add the cluster, so they try to auth with the vanilla cluster dex instance against a cluster running its own separate instance of dex. It ends in tears. So when you have two different clusters running two versions of dex (or anything that does the same such as maybe keycloak), the manual instructions kuberos provides are actually incorrect.

The only tricky part is the CA as `kubectl config set-cluster --help` doesn't appear to show a way to simply add the ca cert data directly. Something like this will suffice if we can work around that:

```bash
# Associate your user with an existing cluster
export CLUSTER=coolcluster
export CONTEXT=coolcontext
kubectl config set-cluster ${CLUSTER} --server=https://ser.ver.path --certificate-authority=/path/to/kube-ca.crt --embed-certs=true

kubectl config set-context ${CONTEXT} --cluster ${CLUSTER} --user="jschroeder@[CENSORED]"
```

Perhaps I'm missing something super obvious here, but the first argument to kuberos is the path to the oidc provider, and since each cluster is self hosting their own, I can't auth both clusters with the same dex instance (or kuberos instance).

**Comment by negz** [comment]
> Perhaps I'm missing something super obvious here, but the first argument to kuberos is the path to the oidc provider, and since each cluster is self hosting their own, I can't auth both clusters with the same dex instance (or kuberos instance).

That's correct. If you have two different OIDC providers (i.e. two different Dex instances) the OIDC flow that Kuberos orchestrates must happen separately for each. Hypothetically Kuberos could support multiple OIDC providers, but the UX would have to change fairly drastically.

With regard to providing instruction to add the clusters, this is the best I've come up with in the past:
```bash
echo MANYLINESOFPEMENCODEDCERTIFICATE  | base64 -D > /tmp/cadata
kubectl config set-cluster coolcluster --server=https://ser.ver.path --certificate-authority=/tmp/cadata --embed-certs=true
```
I'd like to support what you suggest, but as you've seen the `set-cluster` command is pretty awkward. I'm going to close this one out because I'm aware of any way to implement it cleanly, but I'm happy to reopen if anyone has ideas about how that could be done.
