### ISSUE TITLE
kuberos error: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by amit-handa** [negz/kuberos#37]
Hello,
I am facing an issue in running kuberos.

```
docker run -d --name kuberos -p 10003:10003 -v ~/cfg:/cfg "negz/kuberos:latest" /kuberos https://k8s.corp.in:32000/dex $OIDC_CLIENT_ID /cfg/secret /cfg/template
```
docker logs -f kuberos

_kuberos: error: cannot create OIDC provider from issuer https://k8s.corp.in:32000/dex: Get https://k8s.corp.in:32000/dex/.well-known/openid-configuration: x509: certificate signed by unknown authority_

How do I fix it ?

**Comment by negz** [comment]
@amit-handa Is it safe to assume https://k8s.corp.in:32000/dex is using a self signed certificate, or a certificate signed by an internal-only CA? If that's the case you will likely need to provide Kuberos with a copy of your CA certificate. I believe you can do so by dropping it into `/etc/ssl/certificates` in the container.

**Comment by amit-handa** [comment]
Hi,
Yes, it is using certificate signed by the apiserver ca cert.
yes, I agree that I need to share the certificate with kuberos container. but how do I do it when starting kuberos pod ?
Thanks for your help

**Comment by negz** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume

@amit-handa I'd try storing your certificate in a Kubernetes ConfigMap and mounting it into your container's `/etc/ssl/certificates` directory.

**Comment by amit-handa** [comment]
Thank you @negz . closing issue.
