### ISSUE TITLE
Need SSL/TLS option.

### ISSUE THREAD

**Issue by evilezh** [negz/kuberos#45]
e.g. h.ServeTLS(..) etc.

**Comment by negz** [comment]
Funnily enough older versions of Kuberos supported natively serving TLS, but I removed that functionality in https://github.com/negz/kuberos/pull/9. I suggest running a simple reverse proxy in front of Kuberos to terminate TLS instead.

**Comment by evilezh** [comment]
Point is, I can exec into container and sniff authentication data (e.g. tcpdump). It is crucial that even between proxy and application data is encrypted. Or some smart network guy who has no access at all, replicates port traffic and can sniff out authentication data.
